services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - 8000:8000

  # app:
  #   build:
  #     context: .
  #     dockerfile: app.Dockerfile
  #   depends_on:
  #     - api
  #   ports:
  #     - 8501:8501

  # mlflow:
  #   image: ghcr.io/mlflow/mlflow:v3.1.1
  #   ports:
  #     - 8080:8080
  #   environment:
  #     MLFLOW_TRACKING_URI: "http://localhost:8080"
  #   volumes:
  #     - ./mlflow:/mlflow
  #   command: mlflow server --backend-store-uri="mlflow/mlruns" --artifacts-destination="mlflow/mlartifacts" --host 0.0.0.0 --port 8080 
