params:
  - params.yaml

stages:
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw
    outs:
      - data/processed_cookbook.pkl

  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - data/processed_cookbook.pkl
    params:
      - model_pipeline
    outs:
      - models/fasttext.model
      - training_metadata.json
    
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - training_metadata.json
    params:
      - model_evaluation
    outs:
      - validation_metadata.json

  model_registering:
    cmd: python src/model_registering.py
    deps:
      - src/model_registering.py
      - validation_metadata.json
    params:
      - model_register