data_preprocessing:
  raw_data_path: data/raw

model_pipeline:
  model_path: models/fasttext.model
  recipe_path: data/processed_cookbook.pkl

  fast_text:
    vector_size: 100
    window: 8
    sg: 0
    epochs: 100
    seed: 1234
    min_count: 1
    bucket: 50000

  model_scoring:
    w_title: 0.1 # Weight for title similarity
    w_cosine: 0.9 # Weight for mean cosine similarity between query and recipe ingredients (mean ingredients)
    idf_top_weights: [0.8, 0.1, 0.1] # Weights for top 3 similar ingredients to borrow IDF from

model_evaluation:
  seed: 42
  k: 10
  relevant_thresh: 0.5

model_register:
  max_runs: 3

model_service:
  n_recs: 30
