channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=25.1
- pip:
  - mlflow==3.1.1
  - bcrypt==4.3.0
  - boto3==1.36.3
  - cloudpickle==3.1.1
  - gensim==4.3.3
  - numpy==1.26.4
  - pandas==2.2.3
  - psutil==5.9.0
  - pyopenssl==25.1.0
  - scikit-learn==1.6.1
  - scipy==1.13.1
name: mlflow-env
